### PR TITLE
Add more complex example that how delay time works

### PR DESCRIPTION
**Pull request by ve3**

### CODE REVIEW

**Comment by dragonmantank** [comment]
Currently the library does not support any anacron-like behavior (mostly because we do not actually run anything, the library just validates expressions and attempts to determine run dates). The example you've added would actually run every minute for the first 15 minutes of every hour every day, it would not introduce a "wiggle" time of 0-15 minutes. 

Is there additional code to this PR that would introduce that? If there is, the syntax proposed would break many systems, as the `-` character is used to denote ranges. I would also need to see a current implementation of a cron system that _does_ allow delays, to best evaluate how that would fit into this library. I try and keep it as close to the reference implementation of `cronie` as possible.

**Comment by ve3** [comment]
I found that many times cron server can run delay in minutes (0 to 10 minutes from real time).
If I set to `0 0 * * *` then that job can be missed when it is delayed.

Here is my implementation.
```php
$CronExpression = new \Cron\CronExpression('0-15 0 * * *', new \Cron\FieldFactory());
$Cron = new \Modules\RdbAdmin\Libraries\Cron();

if ($CronExpression->isDue() && !$Cron->hasRun()) {// $Cron->hasRun() is for checking that cache already expired.
    // my job, example: delete trash data.

    $Cron->writeCache($ttl);// $ttl is (total seconds before next hour - 1 minute for cache expire before).
}
```

With this, it can run only once per hour.

**Comment by dragonmantank** [comment]
Understood. This is still not how the library nor this syntax is meant to be used, and is not a use case I would support for the vast majority of people. The fact it is working for you this way is a happy coincidence, and unfortunately not something that I can or will support.

A more sustainable solution would be for you to extend the `\Cron\CronExpression` class and override the `isDue()` method to check like +-15 minutes or something. This would allow you to still use a standard expression that wouldn't cause any confusion, and it would be much more apparent what is going on.

However, if the system level cron is not firing jobs every minute (which is how most people use this library), then you or your system administrator will need to debug that at that level. Most cron implementations should have their own logging, so I would start there with some sample jobs that maybe just dump to their own file.

**Comment by ve3** [comment]
I don't know how is this meant to be used. From description and example in the readme, I cannot see any example that how is this meant to be used.

**Comment by dragonmantank** [comment]
So for your specific problem, there is no example because this library does not provide support for drift like you need. It does not, and will not, compensate for that. You will need to extend the library to add in support for checking times with drift. 

All this library does is:

1. Validate that a given expression is syntactically and semantically correct
2. Tell you if the current/given time would match the expression
3. Help calculate future run dates of a given expression.

For the specific example of `0-15 * * * *` and the functionality of this library would tell you:

1. This is a valid cron expression
2. This would match any time that is of the first 0-15 minutes of any hour, of any day, of any month.
3. What the next calculated run time would be (As of the time of this writing, `2019-12-09 14:14:00 GMT`, the next three would be `2019-12-09 14:15:00`, `2019-12-09 15:00:00`, , `2019-12-09 15:01:00`)

I hope that helps. Unfortunately this library can't solve your exact problem because the problem is outside of the scope of this library.

**Pull request closed without merging**
