### PR TITLE
Introduce FieldFactoryInterface

### PR DESCRIPTION
**Pull request by holtkamp**
Backwards compatible introduction of a FieldFactoryInterface.

### CODE REVIEW

**Comment by dragonmantank** [comment]
Hello!

I'm not 100% sure why we would need this, as there isn't normally a reason to have multiple types of factories that you'd be swapping out. Why do we need an interface here?

**Comment by holtkamp** [comment]
@dragonmantank hey!

Well, I encountered the need to have a custom FieldFactory in order to migrate to from `1.x` to `2.x` in which the `year` part is deprecated. (also see https://github.com/dragonmantank/cron-expression/issues/36)

We got CRON expressions which included the `year` part persisted in a database, for example:

`* * * * * *`

```
*    *    *    *    *    *
-    -    -    -    -    -
|    |    |    |    |    |
|    |    |    |    |    + year [optional]
|    |    |    |    +----- day of week (0 - 7) (Sunday=0 or 7)
|    |    |    +---------- month (1 - 12)
|    |    +--------------- day of month (1 - 31)
|    +-------------------- hour (0 - 23)
 +------------------------- min (0 - 59)
```

As of version `2.0.0` using such string to initialize a CronExpression will generate an error since the `year` part is not supported anymore. My idea was to (temporarily) use a custom FieldFactory which simply ignores the `year` part in a expression and then persist a serialized version of the CRON Expression back to the database which does not have the`year` part, so:

`* * * * * *` then becomes 
`* * * * *` => compatible with `2.x`

A FieldFactoryInterface provides some flexibility which would allow users to deal with such situations...

**Comment by holtkamp** [comment]
@dragonmantank what are your thoughts on this? It simply provides some flexibility to use in user-land code...

**Comment by holtkamp** [comment]
Ping @dragonmantank ?

**Comment by holtkamp** [comment]
@dragonmantank updated this PR. Hopefully that together with https://github.com/dragonmantank/cron-expression/pull/38#issuecomment-478362344 this makes sense now: it facilitates easy migration to this fork.

**Comment by dragonmantank** [comment]
Merged this in. Sorry for the delay!

**Pull request merged**
