### PR TITLE
Add PHP_CodeSniffer

### PR DESCRIPTION
**Pull request by holtkamp**
I think it is useful to have working PHPCS functionality in the project it self, which can now simply be executed using:

`composer phpcs` for a dry run
`composer phpcs-fix` for actual fixing. 

For now only applied @PSR2

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why not just enable [StyleCI](https://styleci.io/). No messing about with config and dependencies then. :)

**Comment by GrahamCampbell** [comment]
It seems StyleCI is already enabled actually. This PR can be closed?

**Comment by dragonmantank** [comment]
@holtkamp Can you rebase this off of current master?

**Comment by GrahamCampbell** [comment]
Why have you called it phpcs. phpcs is a different tool to php-cs-fixer?

**Comment by GrahamCampbell** [comment]
StyleCI also has a local CLI Tool now too btw.

**Comment by holtkamp** [comment]
@GrahamCampbell 

>Why have you called it phpcs. phpcs is a different tool to php-cs-fixer?

Indeed, it has a bit more options:

- [`php-cs-fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer)
- [`phpcs`](https://github.com/squizlabs/PHP_CodeSniffer)

**Comment by GrahamCampbell** [comment]
I don't think you understand my complaint? You have installed php-cs-fixer, but your PR and files say phpcs...

**Comment by holtkamp** [comment]
@GrahamCampbell you are right, seems best to close this PR then...

**Pull request closed without merging**
