### PR TITLE
set phpstan to level max and fix issues

### PR DESCRIPTION
**Pull request by oallain**
Hello,

I do: 
* Set PHPStan to level max (ie 8) https://phpstan.org/user-guide/rule-levels.
* Fix issues throws by PHPStan
* Add PHPStan to Travis

It improve DX :rocket:

### CODE REVIEW

**Comment by oallain** [comment]
Hello @dragonmantank,

I use this librairie and i love it, so i propose my first PR :)
I hope this will help you, and i'm available for more updates.

Regards

**Comment by dragonmantank** [comment]
Thanks! Could you possibly rebase on the newest `master` branch? After your PR was created there was an update to support PHP 8, which generated a few conflicts

**Comment by oallain** [comment]
Hello @dragonmantank ,

I've juste rebase on master :tada: 

I'll propose an other PR to add PHPStan chek with Github Actions.

PS : It would be nice for me if you add the "hacktoberfest-accepted" label to this PR.

**Comment by oallain** [comment]
Hello @dragonmantank 

Do you have any time to review this PR?

Thanks

**Comment by dragonmantank** [comment]
Manually merged this, just had a few cleanup issues due to other fixes. Thanks!

**Comment by oallain** [comment]
Good job @dragonmantank 💪
Thanks for that !

**Pull request merged**
